### ISSUE TITLE
separate llm models packages from the main dependencies

### ISSUE THREAD

**Issue by MAfarrag** [Serapieum-of-alex/llama-utils#5]
- All the dependencies are listed under the main dependency part in the pyproject.toml including different LLM packages.
- Since the user will not use all the models simultaneously, usually uses one on the models.
-  the following packages needs to be moved to a separate dependency group.
```toml
llama-index-llms-ollama = "^0.5.0"
llama-index-embeddings-huggingface = "^0.5.1"
llama-index-llms-azure-openai = "^0.3.0"
llama-index-embeddings-azure-openai = "^0.3.0"
```
- do not list the above packages in the conda-forge dependency list
